version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: eflower
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5431:5432
    restart: unless-stopped