name: flutter_boilerplate
description: A simple boilerplate project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  connectivity_plus: ^2.3.0
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_secure_storage: 5.0.2
  get: ^4.6.5
  intl: ^0.17.0
  json_annotation: 4.5.0
  meta: ^1.7.0
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.12
  sizer: ^2.0.15
  auto_size_text: ^3.0.0
  image_picker: ^0.8.5+3
  getwidget: 2.1.1
  adaptive_dialog: ^1.6.3
  flutter_screenutil: ^5.5.3+2
  line_awesome_flutter: ^2.0.0
  animated_theme_switcher: ^2.0.6
  geolocator: 7.7.1
  photo_view: ^0.14.0
  web_socket_channel: ^2.4.0
  multi_select_flutter: ^4.1.3

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.8.1
  dependency_validator: ^3.1.2
  flutter_gen_runner: ^4.2.1+1
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  import_sorter: ^4.6.0
  json_serializable: ^6.2.0
  logger: ^1.1.0
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0
  very_good_performance: ^0.0.4

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  #  integrations:
  #    flutter_svg: true
  #    flare_flutter: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: false
    inputs:
      - assets/color/colors.xml
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/env/.env.production
    - assets/env/.env.staging
    - assets/env/.env.development
    - assets/env/
    - assets/
    - assets/image/
