export enum OrderStatusEnum {
    ALL = '',
    NEW = 'NEW',
    DOING = 'DOING',
    DONE = 'DONE',
    CUSTOMER_SATISFIED = 'CUSTOMER_SATISFIED',
    CUSTOMER_REJECTED = 'CUSTOMER_REJECTED',
    SALE_REJECTED = 'SALE_REJECTED',
    SHIPPING = 'SHIPPING',
    SHIPPED_WITH_PAYMENT = 'SHIPPED_WITH_PAYMENT',
    SHIPPED_WITH_NONPAYMENT = 'SHIPPED_WITH_NONPAYMENT',
    ERROR = 'ERROR',
    FINISHED = 'FINISHED',
}